In [3]:
import numpy as np

In [4]:
a=np.array([(0,1,3),(0,5,6),(6,3,7)])
b =np.array([(3,4,5),(56,5,6),(4,6,7)])

In [7]:
a.ndim

2

In [8]:
a.shape

(3, 3)

In [9]:
a.size

9

In [10]:
a.dtype.name

'int32'

In [11]:
c=a+b

In [12]:
print(c)

[[ 3  5  8]
 [56 10 12]
 [10  9 14]]


In [5]:
d=b**2

In [14]:
print(d)

[[   9   16   25]
 [3136   25   36]
 [  16   36   49]]
